/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unesc.aplicacao;

import javax.swing.JInternalFrame;
import net.unesc.utilidades.Notificacao;
import net.unesc.utilidades.Tela;

/**
 *
 * @author TI
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public TelaMenuPrincipal() {
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPane = new javax.swing.JDesktopPane();
        jlLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmCadUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jdPane.setBackground(new java.awt.Color(255, 255, 255));
        jdPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdPane.setOpaque(false);

        jlLogo.setBackground(new java.awt.Color(255, 255, 255));
        jlLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unesc/resources/logoUnesc.png"))); // NOI18N
        jdPane.add(jlLogo);
        jlLogo.setBounds(350, 80, 570, 440);

        jMenu1.setText("Funções");
        jMenu1.setEnabled(false);

        jMenu3.setText("Cadastros");

        jmCadUsuario.setText("Usuário");
        jmCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jmCadUsuario);

        jMenu1.add(jMenu3);

        jMenuItem1.setText("Eventos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPane, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPane, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jmCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadUsuarioActionPerformed
        JInternalFrame jfCadUsuario = new TelaUsuario();
        this.jdPane.add(jfCadUsuario);
//        Tela.centralizar(jfCadUsuario);
        jfCadUsuario.show();
    }//GEN-LAST:event_jmCadUsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JInternalFrame jfEvento = new TelaEvento();
        JInternalFrame jfRegra = new TelaRegra();
        this.jdPane.add(jfEvento);
        this.jdPane.add(jfRegra);
        Tela.centralizar(jfEvento);
        Tela.centralizar(jfRegra);
        jfEvento.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
//    public static void main(String args[]){
//        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Metal".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                TelaMenuPrincipal menu = new TelaMenuPrincipal();
//                menu.setVisible(true);
//                menu.setExtendedState(MAXIMIZED_BOTH);         
//                menu.jdPane.setBounds(menu.getBounds());
//                menu.jdPane.setPreferredSize(menu.getPreferredSize());
//                JInternalFrame jfLogar = new TelaLogin();
//                menu.jdPane.add(jfLogar);
//                Tela.centralizar(jfLogar);
//                jfLogar.show();
//
//                Tela.centralizar(jlLogo);
////                
////                TelaPadrao telaPadrao = new TelaPadrao();
////                menu.jdPane.add(telaPadrao);
////                Tela.centralizar(telaPadrao);
////                telaPadrao.show();
//            }
//        });
//    }
    
    Notificacao notificacao   = new Notificacao();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JDesktopPane jdPane;
    public static javax.swing.JLabel jlLogo;
    private javax.swing.JMenuItem jmCadUsuario;
    // End of variables declaration//GEN-END:variables
}
